// <auto-generated />
using ChessWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessWebApp.Migrations
{
    [DbContext(typeof(MvcGameContext))]
    [Migration("20230106183141_2-Beta")]
    partial class _2Beta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChessWebApp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerBottomId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerBottomId");

                    b.HasIndex("PlayerTopId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("ChessWebApp.Models.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("ActionId")
                        .HasColumnType("smallint");

                    b.Property<string>("ActionValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameEvent");
                });

            modelBuilder.Entity("ChessWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserChessboardId")
                        .HasColumnType("int");

                    b.Property<short>("VariantBishopLeft")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantBishopRight")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantKing")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantKnightLeft")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantKnightRight")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn1")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn2")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn3")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn4")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn5")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn6")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn7")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantPawn8")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantQueen")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantRookLeft")
                        .HasColumnType("smallint");

                    b.Property<short>("VariantRookRight")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("ChessWebApp.Models.Game", b =>
                {
                    b.HasOne("ChessWebApp.Models.User", "PlayerBottom")
                        .WithMany("GamesBottom")
                        .HasForeignKey("PlayerBottomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChessWebApp.Models.User", "PlayerTop")
                        .WithMany("GamesTop")
                        .HasForeignKey("PlayerTopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlayerBottom");

                    b.Navigation("PlayerTop");
                });

            modelBuilder.Entity("ChessWebApp.Models.GameEvent", b =>
                {
                    b.HasOne("ChessWebApp.Models.Game", "Game")
                        .WithMany("GameEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessWebApp.Models.Game", b =>
                {
                    b.Navigation("GameEvents");
                });

            modelBuilder.Entity("ChessWebApp.Models.User", b =>
                {
                    b.Navigation("GamesBottom");

                    b.Navigation("GamesTop");
                });
#pragma warning restore 612, 618
        }
    }
}
